### PR TITLE
Improve prompt

### PR DESCRIPTION
**Pull request by romkatv**
1. Generate a new p10k config with additional features and fixes from upstream.
2. Allow users to customize prompt with `p10k configure`.
3. Always use powerlevel10k. This gives users functionally the same prompt everywhere. Prompt differs among terminals only in presentation.
4. Don't fork. Forking is slow.
5. Use more robust detection of terminal capabilities.
6. Always use zsh-autosuggestions and ensure that its style is within the terminal's capabilities.

Disclaimer: I'm the owner of https://github.com/romkatv/powerlevel10k.

### CODE REVIEW

**Comment by yochananmarqos** [comment]
@romkatv Thanks! I've applied this as a patch to our package with `manjaro-zsh-config` 0.21-2. It's is now available in the Manjaro unstable branch.

**Comment by romkatv** [comment]
That was fast! Thanks.

**Comment by Chrysostomus** [comment]
Thank you very much for the contribution, it is always a pleasure to work with the upstream!

**Comment by romkatv** [comment]
I just realized I introduced a bug here: `USE_POWERLINE=false` is no longer respected. https://github.com/Chrysostomus/manjaro-zsh-config/pull/31 fixes it. Sorry about that. I've tested it better this time.

**Comment by yochananmarqos** [comment]
Received some [feedback](https://forum.manjaro.org/t/unstable-update-2021-11-11-gnome-41-1-xorg-server-21-1-lxqt-1-0-nvidia-470-86-plasma-5-23-3/89894/23) on the forum. Not sure why it would have prompted him to reconfigure, it didn't for me.

**Comment by romkatv** [comment]
> Received some [feedback](https://forum.manjaro.org/t/unstable-update-2021-11-11-gnome-41-1-xorg-server-21-1-lxqt-1-0-nvidia-470-86-plasma-5-23-3/89894/23) on the forum. Not sure why it would have prompted him to reconfigure, it didn't for me.

Ouch. Thanks for tagging me. I've asked for more info on the forum. At this point I don't have a theory what might have caused `p10k configure` to trigger.

**Comment by Falav** [comment]
Dump provided:
[dump.tar.gz](https://github.com/Chrysostomus/manjaro-zsh-config/files/7537595/dump.tar.gz)

**Comment by romkatv** [comment]
@Falav Thanks! I reproduced this issue with your files. (For context: I've asked Falav in https://forum.manjaro.org/t/issues-with-latest-manjaro-zsh-config-update/90405/6?u=romkatv to post this dump here.)

@yochananmarqos Somehow updating this package resulted in the following structure:

```text
/usr
└── share
    └── zsh
        └── p10k.zsh
            └── p10k.zsh
```

The leaf `p10k.zsh` has the same content as https://github.com/Chrysostomus/manjaro-zsh-config/blob/b6990f0b78d7610c84f494395fc7889f9f8a1e34/p10k.zsh. Why is it at `/usr/share/p10k.zsh/p10k.zsh` rather than `/usr/share/p10k.zsh`?

I also just realized that `p10k-portable.zsh` needs to be added to https://github.com/Chrysostomus/manjaro-zsh-config/blob/master/PKGBUILD. Can you do that or do you want me to send a PR?

**Comment by romkatv** [comment]
@yochananmarqos I think [this change](https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/commit/d9c23e4b691847a70afea9e2b03bc1dd61b9dbba#9b9baac1eb9b72790eef5540a1685306fc43fd6c_39_42) broke it. The trailing `p10k.zsh` needs to be removed from that line. Also, as I mentioned in the previous comment, `p10k-portable.zsh` needs to be installed alongside `p10k.zsh`.

**Comment by pheiduck** [comment]
> @yochananmarqos I think [this change](https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/commit/d9c23e4b691847a70afea9e2b03bc1dd61b9dbba#9b9baac1eb9b72790eef5540a1685306fc43fd6c_39_42) broke it. The trailing `p10k.zsh` needs to be removed from that line. Also, as I mentioned in the previous comment, `p10k-portable.zsh` needs to be installed alongside `p10k.zsh`.

MR is created on gitlab: https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/merge_requests/4/diffs

**Comment by yochananmarqos** [comment]
@romkatv Oops. 

@pheiduck Thanks for fixing it. 0.21-5 is pushed to unstable now.

**Comment by Falav** [comment]
Following the forum thread, I tried to update to 0-22.2 version, but as my file /usr/share/p10k.zsh was already existing, the update aborted.
Maybe a next version could handle a replacement/overwrite of an existing file.

**Comment by yochananmarqos** [comment]
@Falav That's because it was an untracked file, and now it's not. Instruct Pacman to overwrite it or remove it manually.

**Comment by Chrysostomus** [comment]
Did you create file yourself, or did the package do that?

**Comment by Falav** [comment]
Between the initial restores, not sure... I'll do that, my zsh folder does not reflect the standard user one, now.

**Pull request merged**
